#!/bin/bash

server=ec2-3

# Preprocess
php pasteRes.php ../web/index-dev.html > ../web/index.html

echo "Syncing..."
ssh root@$server "mkdir -pv /Projects/FindMe/web"
rsync -avz --delete --exclude=".git" --exclude=".DS_Store" --exclude="*.tmp" \
  /Projects/FindMe/web/ \
  root@$server:/Projects/FindMe/web/
